person:
  userName: 'zhangsan \n李四'
# 单引号会将 \n 作为字符串输出 双引号会将\n 作为换行输出
# 双引号不会转义,单引号会转义
  boss: true
  birth: 2019/12/9
  age: 18
#  interests: [篮球,足球]
  interests:
    - 篮球
    - 足球
    - 羽毛球
  animal: [阿毛，阿狗]
#  score:
#    english: 80
#    math: 90
  score: {english: 80,math: 90}
  salarys:
    - 9999.98
    - 9999.99
  pet:
    name: 小黑
    weight: 99.98
  allpets:
    sick:
      - {name: 阿狗,weight: 99.99}
      - name: 阿猫
        weight: 88.88
      - name: 阿黄
        weight: 89.88
    health:
      - {name: 阿花,weight: 199.99}
      - {name: 阿从,weight: 199.99}